### ISSUE TITLE
Make -t a default

### ISSUE THREAD

**Issue by shark0der** [andris9/nodemailer-sendmail-transport#2]
Sendmail was refusing to deliver any mail and was exiting with 64 until I added `-t` (ubuntu 16.04).

It seems this might also help prevent other possible bugs on the long run: http://serverfault.com/questions/370935/how-to-sendmail-via-command-line-piping#comment717703_370936

**Comment by andris9** [comment]
There are tons of implementations out there that pretend to be `sendmail` and all of these have different quirks. This module had `-t` on by default several years ago and it caused a lot of problems with pre-generated envelopes. At most I'm willing to add a note to README about the `-t` flag but otherwise I'm not touching this code anymore (unless I could test all different `sendmail` implementations).

**Comment by shark0der** [comment]
Fair enough, a bold note in readme about `-t` would do it in hopes that others won't waste an hour like I did :)
Thanks!
