### ISSUE TITLE
sendmail not found

### ISSUE THREAD

**Issue by rfc2822** [andris9/nodemailer-sendmail-transport#4]
When using NodeBB with nodemailer-sendmail-transport (which is the default), there's often a ENOENT ("Sendmail not found") error (see https://github.com/NodeBB/NodeBB/issues/5181).

Unfortunately, I don't have steps to reproduce, because sometimes, it works for some time and then it doesn't work anymore ("sendmail not found"). Setting the `path` to the absolute path of the sendmail executable seems to fix it, but I don't know for how long.

Do you know a way to debug this?

**Comment by andris9** [comment]
sendmail is called using [child_process.spawn(command,…)](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) and the command to run by default is 'sendmail'. If node can't find it for whatever reason (usually because the sendmail executable is not in $PATH) then you get ENOENT. There's not much the module itself could do in that case, you have to provide the full path and hope it fixes it. If you have also a local MTA running then I would suggest using SMTP not sendmail to deliver email.

**Comment by rfc2822** [comment]
As I have described in the NodeBB issue, the problem is that sendmail *is* found at the beginning and after a few hours/days, it's suddenly not found anymore. This breaks sending emails at a time I don't know, which makes the forum very unreliable.

But just forget it, I'll find out myself, thanks.
